name: Build README and deploy Datasette

on:
  push:
    branches:
    - main
    paths-ignore:
    - README.md

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v5
      # We need full history to introspect created/updated:
      with:
        fetch-depth: 0  
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: 3.12
    - uses: actions/cache@v4
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build database
      run: python build_database.py
    - name: Update README
      run: |-
        python update_readme.py --rewrite
        cat README.md
    - name: Commit and push if changed
      run: |-
        git diff
        git config --global user.email "readme-bot@example.com"
        git config --global user.name "🤖 README-bot"
        git diff --quiet || (git add README.md tils.db && git commit -m "Updated README and database")
        git push
